export const CARD_TYPES = {
  Thesis: "立论",
  Argument: "论证",
  Counter: "反制",
  Label: "定性",
  Redirect: "转进",
  Finisher: "终结",
};

export const KEYWORD_LABELS = {
  response: "回应",
  redirect: "转进",
  label: "定性",
  momentumShift: "带节奏",
  stubborn: "嘴硬",
  bringUpPast: "翻旧账",
};

export const STATUS_META = {
  urgent: {
    name: "急了",
    tone: "bad",
    description: "攻击类牌会让自己额外 +1 破防；反制数值 -1。",
  },
  doubleStandard: {
    name: "双标",
    tone: "bad",
    description: "连续打出同类型牌时，额外损失 1 点舆论。",
  },
  stubborn: {
    name: "嘴硬",
    tone: "good",
    description: "体面低于 10 时攻击牌 +2，但无法回复体面。",
  },
  speechless: {
    name: "失语",
    tone: "bad",
    description: "下一张【回应】牌无法使用。",
  },
  mainNarrative: {
    name: "主叙事",
    tone: "good",
    description: "【带节奏】类牌额外 +1 效果。",
  },
  labeled: {
    name: "已挂标签",
    tone: "bad",
    description: "会被【翻旧账】类牌额外利用。",
  },
  lastWord: {
    name: "还没结束",
    tone: "good",
    description: "暂时不会因体面归零失败，并在失守后回 1 点体面。",
  },
};

function makeCard(definition) {
  return definition;
}

export const ALL_CARDS = [
  makeCard({
    id: "you-urgent",
    name: "你急了",
    cost: 1,
    type: "Label",
    target: "enemy",
    context: "normal",
    keywords: ["label"],
    description: "使目标获得【急了】1 回合，并增加 2 点破防。",
    effects: [
      { id: "applyStatus", status: "urgent", duration: 1, target: "enemy" },
      { id: "tilt", value: 2, target: "enemy" },
    ],
  }),
  makeCard({
    id: "ask-first",
    name: "先问是不是",
    cost: 1,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "使一张敌方论证牌伤害 -2。",
    effects: [{ id: "reducePendingFace", value: 2 }],
  }),
  makeCard({
    id: "where-data",
    name: "数据呢",
    cost: 1,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "造成 3 点体面伤害；若你本回合拥有主叙事，再造成 1 点舆论变化。",
    effects: [
      { id: "dealFace", value: 3, target: "enemy" },
      { id: "opinionIfSelfHasStatus", status: "mainNarrative", value: 1 },
    ],
  }),
  makeCard({
    id: "whatabout",
    name: "顾左右而言他",
    cost: 1,
    type: "Redirect",
    target: "enemy",
    context: "response",
    keywords: ["response", "redirect"],
    description: "将一张指向你体面的牌，改为影响舆论 2 点。",
    effects: [{ id: "convertPendingFaceToOpinion", value: 2 }],
  }),
  makeCard({
    id: "ponder",
    name: "我寻思",
    cost: 0,
    type: "Thesis",
    target: "self",
    context: "normal",
    keywords: [],
    description: "获得 1 点气势，抽 1 张牌。",
    effects: [
      { id: "gainMomentum", value: 1, target: "self" },
      { id: "draw", value: 1, target: "self" },
    ],
  }),
  makeCard({
    id: "double-warning",
    name: "双标警告",
    cost: 2,
    type: "Label",
    target: "enemy",
    context: "normal",
    keywords: ["label"],
    description: "目标获得【双标】2 回合。",
    effects: [{ id: "applyStatus", status: "doubleStandard", duration: 2, target: "enemy" }],
  }),
  makeCard({
    id: "quote-out",
    name: "断章取义",
    cost: 1,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "取消对方牌的附加效果，仅保留基础数值。",
    effects: [{ id: "cancelPendingBonus" }],
  }),
  makeCard({
    id: "calm-down",
    name: "你先别急",
    cost: 1,
    type: "Counter",
    target: "self",
    context: "normal",
    keywords: [],
    description: "你失去 1 点破防，并获得 3 点格挡体面伤害。",
    effects: [
      { id: "reduceTilt", value: 1, target: "self" },
      { id: "gainBlock", value: 3, target: "self" },
    ],
  }),
  makeCard({
    id: "classic-redirect",
    name: "经典转进",
    cost: 2,
    type: "Redirect",
    target: "self",
    context: "normal",
    keywords: ["redirect"],
    description: "本回合你下一张论证牌改为“造成等量舆论变化”。",
    effects: [{ id: "setNextArgumentToOpinion" }],
  }),
  makeCard({
    id: "quote-old-post",
    name: "引用旧帖",
    cost: 2,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: ["bringUpPast"],
    description: "造成 4 点体面伤害；若目标已有状态，则额外 +2。",
    effects: [{ id: "dealFaceIfTargetHasStatus", base: 4, bonus: 2, target: "enemy" }],
  }),
  makeCard({
    id: "not-serious",
    name: "没必要这么认真",
    cost: 1,
    type: "Thesis",
    target: "self",
    context: "normal",
    keywords: [],
    description: "降低自己 2 点破防，并摸 1 张牌。",
    effects: [
      { id: "reduceTilt", value: 2, target: "self" },
      { id: "draw", value: 1, target: "self" },
    ],
  }),
  makeCard({
    id: "logic-leap",
    name: "逻辑跳跃",
    cost: 2,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "使敌方一张牌失效；若其费用 ≥3，则你获得 1 点舆论。",
    effects: [
      { id: "counterPending" },
      { id: "opinionIfPendingCostAtLeast", threshold: 3, value: 1 },
    ],
  }),

  makeCard({
    id: "set-pace",
    name: "带节奏",
    cost: 1,
    type: "Thesis",
    target: "enemy",
    context: "normal",
    keywords: ["momentumShift"],
    description: "舆论 +2。",
    effects: [{ id: "gainOpinion", value: 2 }],
  }),
  makeCard({
    id: "main-narrative",
    name: "主叙事",
    cost: 2,
    type: "Thesis",
    target: "self",
    context: "normal",
    keywords: [],
    description: "你获得【主叙事】2 回合。",
    effects: [{ id: "applyStatus", status: "mainNarrative", duration: 2, target: "self" }],
  }),
  makeCard({
    id: "hot-search",
    name: "热搜体质",
    cost: 2,
    type: "Thesis",
    target: "self",
    context: "normal",
    keywords: ["momentumShift"],
    description: "舆论 +1，抽 1 张；若当前舆论领先，再抽 1 张。",
    effects: [
      { id: "gainOpinion", value: 1 },
      { id: "draw", value: 1, target: "self" },
      { id: "drawIfLeading", value: 1, target: "self" },
    ],
  }),
  makeCard({
    id: "group-consensus",
    name: "群体共识",
    cost: 3,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "若舆论 ≥2，对目标造成 6 点体面伤害，否则造成 3 点。",
    effects: [{ id: "dealFaceIfOpinionAtLeast", threshold: 2, base: 3, bonus: 3, target: "enemy" }],
  }),
  makeCard({
    id: "everyone-knows",
    name: "大家都懂",
    cost: 4,
    type: "Finisher",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "若舆论 ≥3，造成 10 点体面伤害，否则仅造成 2 点。",
    effects: [{ id: "dealFaceIfOpinionAtLeast", threshold: 3, base: 2, bonus: 8, target: "enemy" }],
  }),
  makeCard({
    id: "raise-intensity",
    name: "上强度了",
    cost: 2,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: ["momentumShift"],
    description: "造成 2 点体面伤害，并使舆论 +2。",
    effects: [
      { id: "dealFace", value: 2, target: "enemy" },
      { id: "gainOpinion", value: 2 },
    ],
  }),
  makeCard({
    id: "opinion-backfire",
    name: "舆情反噬",
    cost: 2,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "若对方当前舆论落后，则其本牌额外承受 2 点破防。",
    effects: [{ id: "tiltIfActorOpinionBehind", value: 2 }],
  }),
  makeCard({
    id: "burst-point",
    name: "节奏爆点",
    cost: 3,
    type: "Finisher",
    target: "enemy",
    context: "normal",
    keywords: ["momentumShift"],
    description: "按当前舆论正值，每点造成 2 点体面伤害，最多 10。",
    effects: [{ id: "dealFaceByPositiveOpinion", per: 2, cap: 10, target: "enemy" }],
  }),

  makeCard({
    id: "snide",
    name: "阴阳怪气",
    cost: 1,
    type: "Label",
    target: "enemy",
    context: "normal",
    keywords: ["label"],
    description: "目标 +3 破防。",
    effects: [{ id: "tilt", value: 3, target: "enemy" }],
  }),
  makeCard({
    id: "poke-spot",
    name: "戳痛点",
    cost: 2,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "造成 2 点体面伤害和 3 点破防。",
    effects: [
      { id: "dealFace", value: 2, target: "enemy" },
      { id: "tilt", value: 3, target: "enemy" },
    ],
  }),
  makeCard({
    id: "break-check",
    name: "破防检测",
    cost: 1,
    type: "Label",
    target: "enemy",
    context: "normal",
    keywords: ["label"],
    description: "若目标破防 ≥5，再追加 2 点体面伤害。",
    effects: [{ id: "dealFaceIfTargetTiltAtLeast", threshold: 5, base: 0, bonus: 2, target: "enemy" }],
  }),
  makeCard({
    id: "dig-history",
    name: "翻旧账",
    cost: 2,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: ["bringUpPast"],
    description: "对有状态目标造成 6 点体面伤害，否则 2 点。",
    effects: [{ id: "dealFaceIfTargetHasStatus", base: 2, bonus: 4, target: "enemy" }],
  }),
  makeCard({
    id: "attach-label",
    name: "挂标签",
    cost: 2,
    type: "Label",
    target: "enemy",
    context: "normal",
    keywords: ["label"],
    description: "使目标获得【已挂标签】并增加 2 点破防。",
    effects: [
      { id: "applyStatus", status: "labeled", duration: 3, target: "enemy" },
      { id: "tilt", value: 2, target: "enemy" },
    ],
  }),
  makeCard({
    id: "keep-hitting",
    name: "追着打",
    cost: 1,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "若目标本回合获得过破防，则造成 4 点体面伤害。",
    effects: [{ id: "dealFaceIfTargetTookTiltThisTurn", value: 4, target: "enemy" }],
  }),
  makeCard({
    id: "cant-hold",
    name: "崩不住了",
    cost: 3,
    type: "Finisher",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "若目标破防 ≥7，立即触发一次失态。",
    effects: [{ id: "forcedComposureIfTiltAtLeast", threshold: 7, target: "enemy" }],
  }),
  makeCard({
    id: "exposed",
    name: "你这就暴露了",
    cost: 1,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "若对方本回合打出过立论牌，使其 +3 破防。",
    effects: [{ id: "tiltIfPendingActorPlayedTypeThisTurn", type: "Thesis", value: 3 }],
  }),

  makeCard({
    id: "not-the-point",
    name: "这不是重点",
    cost: 1,
    type: "Redirect",
    target: "enemy",
    context: "response",
    keywords: ["response", "redirect"],
    description: "使敌方下一次体面伤害改为破防伤害。",
    effects: [{ id: "convertPendingFaceToTilt" }],
  }),
  makeCard({
    id: "we-are-discussing",
    name: "我们讨论的是",
    cost: 2,
    type: "Redirect",
    target: "self",
    context: "normal",
    keywords: ["redirect"],
    description: "本回合你的下一张牌额外获得【带节奏】。",
    effects: [{ id: "setNextCardOpinionBonus", value: 1 }],
  }),
  makeCard({
    id: "shift-meaning",
    name: "偷换概念",
    cost: 2,
    type: "Redirect",
    target: "enemy",
    context: "normal",
    keywords: ["redirect"],
    description: "将目标一个持续状态替换成另一个随机负面状态。",
    effects: [{ id: "replaceTargetStatus", target: "enemy" }],
  }),
  makeCard({
    id: "redefine",
    name: "重新定义",
    cost: 2,
    type: "Counter",
    target: "enemy",
    context: "normal",
    keywords: [],
    description: "使一个敌方增益效果失效，并获得 1 点舆论。",
    effects: [
      { id: "removeEnemyBuff", target: "enemy" },
      { id: "gainOpinion", value: 1 },
    ],
  }),
  makeCard({
    id: "dont-derail",
    name: "别带偏了",
    cost: 1,
    type: "Counter",
    target: "enemy",
    context: "response",
    keywords: ["response"],
    description: "取消一次敌方【转进】效果。",
    effects: [{ id: "cancelPendingRedirect" }],
  }),
  makeCard({
    id: "topic-swap",
    name: "话题切换",
    cost: 3,
    type: "Redirect",
    target: "none",
    context: "normal",
    keywords: ["redirect", "momentumShift"],
    description: "交换双方当前舆论值的符号。",
    effects: [{ id: "flipOpinion" }],
  }),

  makeCard({
    id: "not-lost",
    name: "我没输",
    cost: 1,
    type: "Thesis",
    target: "self",
    context: "normal",
    keywords: ["stubborn"],
    description: "若你的体面 ≤10，获得 2 气势并抽 1 张牌。",
    effects: [{ id: "gainMomentumAndDrawIfFaceAtMost", threshold: 10, momentum: 2, draws: 1 }],
  }),
  makeCard({
    id: "stubborn-end",
    name: "嘴硬到底",
    cost: 2,
    type: "Label",
    target: "self",
    context: "normal",
    keywords: ["stubborn"],
    description: "你获得【嘴硬】2 回合。",
    effects: [{ id: "applyStatus", status: "stubborn", duration: 2, target: "self" }],
  }),
  makeCard({
    id: "force-explain",
    name: "强行解释",
    cost: 2,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: ["stubborn"],
    description: "造成 4 点体面伤害；若你体面 ≤10，则改为 7 点。",
    effects: [{ id: "dealFaceIfFaceAtMost", threshold: 10, base: 4, bonus: 3, target: "enemy" }],
  }),
  makeCard({
    id: "headwind-output",
    name: "逆风输出",
    cost: 3,
    type: "Argument",
    target: "enemy",
    context: "normal",
    keywords: ["stubborn"],
    description: "基础造成 3 点体面伤害，并按你已损失体面的 1/3 追加伤害，最多 +6。",
    effects: [{ id: "dealFaceWithLostFaceBonus", base: 3, divisor: 3, cap: 6, target: "enemy" }],
  }),
  makeCard({
    id: "not-over",
    name: "还没结束",
    cost: 2,
    type: "Counter",
    target: "self",
    context: "normal",
    keywords: ["stubborn"],
    description: "你暂时不会因体面归零失败；若本轮被打空，会回 1 点体面。",
    effects: [{ id: "preventDefeat", duration: 1, target: "self" }],
  }),
  makeCard({
    id: "win-hard",
    name: "赢麻了",
    cost: 5,
    type: "Finisher",
    target: "enemy",
    context: "normal",
    keywords: ["stubborn"],
    description: "若你体面 ≤8，造成 12 点体面伤害；否则造成 5 点。",
    effects: [{ id: "dealFaceIfFaceAtMost", threshold: 8, base: 5, bonus: 7, target: "enemy" }],
  }),
];

export const CARD_LIBRARY = Object.fromEntries(ALL_CARDS.map((card) => [card.id, card]));

export const PLAYER_STARTER_DECK = [
  "you-urgent",
  "you-urgent",
  "ponder",
  "ponder",
  "where-data",
  "where-data",
  "calm-down",
  "calm-down",
  "whatabout",
  "whatabout",
  "set-pace",
  "set-pace",
  "poke-spot",
  "poke-spot",
  "force-explain",
  "force-explain",
  "quote-out",
  "win-hard",
];

export const BATTLEFIELDS = {
  "comment-zone": {
    id: "comment-zone",
    name: "评论区",
    rules: [
      "所有【带节奏】牌效果 +1。",
      "所有【回应】牌费用 -1，最低为 0。",
    ],
  },
  "group-chat": {
    id: "group-chat",
    name: "群聊",
    rules: [
      "每回合行动方额外抽 1 张牌。",
      "每次失态，额外损失 1 点舆论。",
    ],
  },
};

export const ENCOUNTERS = [
  {
    id: "nitpicker",
    name: "杠精",
    role: "高回应 / 拆字眼",
    face: 22,
    battlefieldId: "comment-zone",
    behavior: "counter",
    deck: [
      "ask-first",
      "ask-first",
      "quote-out",
      "logic-leap",
      "logic-leap",
      "dont-derail",
      "redefine",
      "redefine",
      "where-data",
      "where-data",
      "quote-old-post",
      "quote-old-post",
      "double-warning",
      "main-narrative",
      "set-pace",
      "whatabout",
    ],
    passive: "喜欢在你的强牌上回一句“来源呢”。",
  },
  {
    id: "traffic-beast",
    name: "流量怪",
    role: "强舆论 / 快压制",
    face: 26,
    battlefieldId: "group-chat",
    behavior: "opinion",
    deck: [
      "set-pace",
      "set-pace",
      "set-pace",
      "main-narrative",
      "main-narrative",
      "hot-search",
      "hot-search",
      "group-consensus",
      "group-consensus",
      "everyone-knows",
      "raise-intensity",
      "raise-intensity",
      "opinion-backfire",
      "opinion-backfire",
      "burst-point",
      "ponder",
    ],
    passive: "只要场面热起来，它就会不停往上拱火。",
  },
  {
    id: "snarklord",
    name: "阴阳人",
    role: "强破防 / 状态连锁",
    face: 28,
    battlefieldId: "comment-zone",
    behavior: "tilt",
    deck: [
      "you-urgent",
      "you-urgent",
      "snide",
      "snide",
      "poke-spot",
      "poke-spot",
      "break-check",
      "break-check",
      "dig-history",
      "dig-history",
      "attach-label",
      "attach-label",
      "keep-hitting",
      "keep-hitting",
      "cant-hold",
      "exposed",
    ],
    passive: "不急着打脸，先把你架到情绪边缘。",
  },
  {
    id: "victory-king",
    name: "精神胜利王",
    role: "Boss / 残血爆发",
    face: 34,
    battlefieldId: "group-chat",
    behavior: "boss",
    deck: [
      "not-lost",
      "stubborn-end",
      "stubborn-end",
      "force-explain",
      "force-explain",
      "headwind-output",
      "headwind-output",
      "win-hard",
      "topic-swap",
      "group-consensus",
      "everyone-knows",
      "opinion-backfire",
      "logic-leap",
      "you-urgent",
      "poke-spot",
      "not-over",
      "main-narrative",
      "burst-point",
    ],
    passive: "体面越低越疯，越残血越危险。",
  },
];

export const NEGATIVE_STATUS_POOL = ["urgent", "doubleStandard", "speechless", "labeled"];
export const POSITIVE_STATUS_POOL = ["stubborn", "mainNarrative", "lastWord"];
export const REWARD_POOL = ALL_CARDS.map((card) => card.id);

export const DEMO_NOTES = [
  "为了让【回应】真正参与决策，防守方在对手回合获得 1 点临时应对气势。",
  "【逆风输出】按“基础 3 + 已损失体面 / 3”计算，最多额外 +6。",
  "【还没结束】在本白盒中会保护你撑过当前交锋，并在被打空时回 1 点体面。",
];
